linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    check-type-assertions: true
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
    check-blank: false
  cyclop:
    # The maximal code complexity to report. Default is 10.
    max-complexity: 15
  tagliatelle:
    case:
      rules:
        json: snake
  loggercheck:
    zap: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosec
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bodyclose
    - cyclop
    - depguard
    - dupl
    - exhaustive
    - nilerr
    - unconvert
    - tagliatelle
    - gocritic
    - loggercheck

run:
  skip-dirs:
    - docs